@host = {{local}}/tasks
@remote = http://workhaus-api.westeurope.azurecontainer.io:7000/v1/tasks
POST {{remote}}/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{companyToken}}

{
    "title": "Graphic design",
    "description": "bla bla bla bla bla bla bla bla",
    "amount": "10",
    "category": "614b3b3c3433aaf413214c1e"
}

###
GET {{remote}}/614b082ce1f12d838bedab06
Accept: application/json
Authorization: Bearer {{adminToken}}

###
GET {{remote}}/sort/category/614b4e7f8ade9529646a87e2
Accept: application/json
Authorization: Bearer {{adminToken}}

### only users can register interests with a task
PATCH {{remote}}/interests/614b082ce1f12d838bedab06
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{userToken}}

### only clients/companies can update the completion of a task
PATCH {{remote}}/completion/614b082ce1f12d838bedab06
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{companyToken}}

{
    "completion": "incomplete"
}

### only users can update the progress of the task
PATCH {{remote}}/progress/614b082ce1f12d838bedab06
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "progress": "starts"
}