@host = {{local}}/tasks
@remote = http://workhaus-api.westeurope.azurecontainer.io/v1/tasks
POST {{host}}/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{companyToken}}

{
    "title": "Graphic design",
    "description": "bla bla bla bla bla bla bla bla",
    "amount": "10",
    "category": "614b3b3c3433aaf413214c1e"
}

###
GET {{host}}/614dd30a879ae119d42f01cc
Accept: application/json
Authorization: Bearer {{userToken}}

###

GET {{remote}}/sort/category/614b4e7f8ade9529646a87e2
Accept: application/json
Authorization: Bearer {{adminToken}}

### only users can register interests with a task
PATCH {{host}}/interests/6156bdda16b56c0b62df6a8e
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{userToken}}

### only clients/companies can update the completion of a task
PATCH {{host}}/completion/6156bdda16b56c0b62df6a8e
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{companyToken}}

{
    "completion": "completed"
}

### only users can update the progress of the task
PATCH {{host}}/progress/614b082ce1f12d838bedab06
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
    "progress": "finishes"
}

### only clients can approve a user's request
PATCH {{host}}/approve/interests/614dd30a879ae119d42f01cc
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{companyToken}}

{
    "status": "approved",
    "user": "614c8b2c8102fdcc8b8b2293"
}