HTTP/1.1 200 OK
Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
X-DNS-Prefetch-Control: off
Expect-CT: max-age=0
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
X-XSS-Protection: 0
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 392
ETag: W/"188-er1o1i2xwwvULnQGaHdJQ9bP63Y"
Date: Wed, 22 Sep 2021 15:52:42 GMT
Connection: close

{"status":200,"message":"Tasks found","data":[{"_id":"614b4e7f8ade9529646a87e2","title":"Graphic design","description":"bla bla bla bla bla bla bla bla","status":"unVerified","attachement":[],"interests":[],"deletedAt":null,"user":"61421f63ac0820d8f463037b","txRef":"151d729a-d3b0-4fb8-b37d-90bf16b09d77","category":"614b3b3c3433aaf413214c1e","createdAt":"2021-09-22T15:40:47.216Z","__v":0}]}