@host = http://localhost:7000/v1/users

POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
   "email": "xeleso3851@shensufu.com",
   "password": "nAdia123"
}
###
POST {{host}}/signup/0
Content-Type: application/json
Accept: application/json

{
   "email": "niwikib754@sicmag.com",
   "password": "alain1231",
   "names": "Alain C",
   "country": "rwanda"
}